### ISSUE TITLE
Problem with Visual Studio 2019 support

### ISSUE THREAD

**Issue by jcarlos-ciber** [MarvelmindRobotics/marvelmind.c#1]
The code builds in Visual Studio 2019 x64 successfully but it does not work.

The problem was detected in the processing of the text string specifying which port to connect to. I had to change the type of the variable ttyFileName from char* to *w_chart_t. 

```cpp
const wchar_t* ttyFileName = TEXT("\\\\.\\COM5");
```
It works. Probably this solution would also work. (no tested)
```cpp
const wchar_t* ttyFileName = L"\\\\.\\COM5";
```
The problem is how to use variables instead of literals. :-(

Would it be possible to officially fix this problem? Thanks! :-)

JC

**Comment by smoker771** [comment]
Fixed in version from 2022.08.02. Now can build in Visual Studio for both x64 and x86
Thank you for the feedback.
