### ISSUE TITLE
IMU fusion Y and Z are being decoded with wrong bit width

### ISSUE THREAD

**Issue by John-Brooks** [MarvelmindRobotics/marvelmind.c#2]
In marvelmind.c `process_imu_fusion_datagram`, the Y and Z data is parsed as 16 bit integers rather than 32 bit integers. The raw data indexing is presumably correct (4 byte separation), and since the data is encoded as little endian you are going to end up reading the 2 least significant bytes of each value, which I believe will just constrain your range of values to +/- 32,767 mm.

```
    hedge->fusionIMU.x= get_int32(&dataBuf[0]);
    hedge->fusionIMU.y= get_int16(&dataBuf[4]);
    hedge->fusionIMU.z= get_int16(&dataBuf[8]);
```
https://github.com/MarvelmindRobotics/marvelmind.c/blob/2ecafed264c7e4be69ab2b71028545a129dea83c/src/marvelmind.c#L489

**Comment by smoker771** [comment]
Fixed in version from 2022.08.02. 
Thank you for the feedback
